services:
  yo-validator:
    image: hyperledger/besu:24.6.0
    container_name: yo-validator
    restart: unless-stopped
    user: "0:0"
    volumes:
      - validator-data:/opt/besu/data
      - ./validator/key:/opt/besu/key:ro
      - ./genesis.json:/config/genesis.json:ro
      - ./static-nodes.json:/config/static-nodes.json:ro
    command: >
      --data-path=/opt/besu/data
      --genesis-file=/config/genesis.json
      --static-nodes-file=/config/static-nodes.json
      --node-private-key-file=/opt/besu/key
      --rpc-http-enabled
      --rpc-http-api=ETH,NET,WEB3,TXPOOL,IBFT
      --rpc-http-cors-origins=*
      --host-allowlist=*
      --rpc-http-port=8545
      --rpc-ws-enabled
      --rpc-ws-port=8546
      --rpc-ws-api=ETH,NET,WEB3,TXPOOL,IBFT
      --p2p-port=30303
      --network-id=2025
      --miner-enabled
      --miner-coinbase=${MINER_COINBASE}
      --logging=INFO
      --p2p-host=0.0.0.0
      --rpc-http-host=0.0.0.0
      --rpc-ws-host=0.0.0.0
    ports:
      - "8545:8545"
      - "8546:8546" 
      - "30303:30303"
    environment:
      - MINER_COINBASE=${MINER_COINBASE}
    networks:
      - yo-network

networks:
  yo-network:
    driver: bridge

volumes:
  validator-data:
    driver: local
